.DEFAULT_GOAL := test

.PHONY: clean html_coverage quality requirements test upgrade

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	coverage erase
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info

html_coverage:
	coverage html && open htmlcov/index.html


requirements:
	redo requirements/install

test:
	redo requirements/django-test.nodjango.txt
	tox

upgrade: ## update the requirements/*.txt files with the latest packages satisfying requirements/*.in
	redo requirements/upgrade
